name: Buf Breaking Changes

on:
  pull_request:
    branches: [main]

jobs:
  breaking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-setup-action@v1
      - run: buf breaking --against 'https://git.vareal.group/VarealGroup/sirosimes-proto.git#branch=main'
